### ISSUE TITLE
This is a sample question that do not need an answer

### ISSUE THREAD

**Issue by gmaze** [euroargodev/publicQCforum#1]
Hi all,
I'd like to know what are the quality tests used to validate Argo measurements ?

**Comment by gmaze-earise** [comment]
Dear @gmaze 
The list of tests used to validate Argo measurements depend on the time since the data was acquired (real time vs delayed time, typically one year) and the data to be validated (temperature, salinity, trajectory, oxygen, etc ...).
So you need to be more precise in your question.
