### ISSUE TITLE
[expert] FORTRAN code for RTQC of bio-optical variables

### ISSUE THREAD

**Issue by cgrdn** [euroargodev/publicQCforum#15]
**Is your QC expertise request related to a problem? Please describe.**
Argo Canada is deploying floats equipped with bio-optics (CHLA, BBP, CDOM) next year. To this point, we have only worked with DOXY in terms of BGC variables, and so we do not have a RTQC method set up for these "new to us" variables. Since our DOXY code is written in FORTRAN, we plan/hope to stay consistent with that. Can anyone share or point me to existing code to do this that we could adapt to our DAC?

**Describe the Argo data you'd like to validate**
Incoming data stream to the MEDS DAC. 

**Describe QC methods you've already considered**
I'm familiar with the RTQC tests for these variables, just don't want to re-write something I am quite sure already exists!

**Additional context**
N/A

**Comment by matdon17** [comment]
FYI, BODC needs to enhance/replace its RTQC toolbox, and is looking at doing so in Python as a complete set.  Would be great to work with anyone who wants to go in this direction.

**Comment by gmaze** [comment]
@cgrdn I'm pretty sure @catsch will be able to point you toward the most appropriate and up to date softwares for RTQC of bgc variables
@catsch, can you please give us a hint here, thanks

**Comment by cgrdn** [comment]
@matdon17 long term I/we at Argo Canada would be interested in working on that with you. For the moment just looking for something that can slide into our existing infrastructure easily, but overall I think we want to push our RTQC toward python as well.

**Comment by gmaze** [comment]
Or may be someone from @euroargodev/bgc_argo_qc can comment on this

**Comment by cgrdn** [comment]
Hi all, there has been some follow up between @catsch and I via email and I feel that we resolved this issue, so I'm going to close it. Thanks!
