### ISSUE TITLE
Area restriction hist data OW

### ISSUE THREAD

**Issue by Alberto-GS** [euroargodev/publicQCforum#20]
Hi all,

I'm doing the DM for float 6901263.

Regarding the historical data, I'd like OW to do not consider data from the Alboran Sea (Western Mediterranean). Indeed it is a different basin from the Atlantic and with higher salinity values, so the analysis can be misinterpreted. I've talking with Cecile about how we can restrict the Med sea area through changing some scripts (get_region_ow.m or find_besthist.m?) and found convenient to ask here if anyone has been in this situation before and how they have solved the problem.

Thanks!

![Screenshot 2023-02-03 at 12 54 13](https://user-images.githubusercontent.com/59921363/217203982-45adfb30-9116-4202-b70e-7e6932bdb613.png)

**Comment by apswong** [comment]
Hi @Alberto-GS.
OW simply looks for ref data within the ellipse specified by your mapping decorrelation scales.  It does not distinguish different ocean basins separated by land masses.  To exclude ref data from the Mediterranean, you'll have to manually remove them from your own version of the ref dbase.

**Comment by Alberto-GS** [comment]
> Hi @Alberto-GS. OW simply looks for ref data within the ellipse specified by your mapping decorrelation scales. It does not distinguish different ocean basins separated by land masses. To exclude ref data from the Mediterranean, you'll have to manually remove them from your own version of the ref dbase.

Thanks!

**Comment by gmaze** [comment]
Hi @Alberto-GS 
If you're ok to work in python, you can also give a try to using a [PCM classifier](https://pyxpcm.readthedocs.io/). 

This is what I get for a PCM on both temperature and salinity profiles between 500 and 1000m depths:
![download](https://user-images.githubusercontent.com/1956032/217524698-eade924b-9b48-4534-bed5-00d14f2fb999.png)

with this method, you can simply filter out automatically all OWC reference profiles from class k=1 to the right.
check this out here: https://github.com/euroargodev/DMQC-PCM

and here are the files to use on OWC with the USE_PCM=1 option:
- [pcm_classes_6901263_K2_Ftemp_Fsal_zmax500_zmin999_argo.txt](https://github.com/euroargodev/publicQCforum/files/10685280/pcm_classes_6901263_K2_Ftemp_Fsal_zmax500_zmin999_argo.txt)
- [ow_config_alberto.txt](https://github.com/euroargodev/publicQCforum/files/10685283/ow_config_alberto.txt)

I can also send you the notebook I used to do this

**Comment by Alberto-GS** [comment]
Thanks [gmaze](https://github.com/gmaze)! Really appreciate it.
